const TIMEOUT_REFRESH_CURRENT_ACTIVITY = 1500;
const CURRENT_ACTIVITY_NOT_SET_VALUE = -9999;
const MAX_ATTEMPS_STATUS_UPDATE = 15;
const DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE = 2000;
const DELAY_TO_UPDATE_STATUS = 500;
const DELAY_LAUNCH_REFRESH = 2500;
const DELAY_BEFORE_RECONNECT = 5000;
const DELAY_FOR_STATELESS_SWITCH_UPDATE = 350;
const DELAY_FOR_SLIDER_UPDATE = 500;
const DELAY_FOR_MACRO = 350;
const DEVICE_TYPE = 'DEVICE';
const ACTIVITY_TYPE = 'ACTVIVITY';
const DEVICEMACRO_TYPE = 'DEVICEMACRO';
const HOME_TYPE = 'HOME';
const SEQUENCE_TYPE = 'SEQUENCE';
const GENERALMUTE_TYPE = 'MUTE';
const GENERALVOLUME_TYPE = 'VOLUME';
const GENERALVOLUMEUP_TYPE = 'VOLUMEUP';
const GENERALVOLUMEDOWN_TYPE = 'VOLUMEDOWN';
const DEFAULT_VOLUME = 50;
const HUB_CONNECT_TIMEOUT = 10000;
const HUB_SEND_TIMEOUT = 30000;
const MAX_SOCKET_ERROR = 5;
const DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS = 60000;
const DELAY_FOR_AUTO_DISCOVERY = 6000;
const PLUGIN_IDENTIFIER = 'homebridge-harmony-hb2';
const PLATFORM_NAME = 'HarmonyHubWebSocket';

export {
  TIMEOUT_REFRESH_CURRENT_ACTIVITY,
  CURRENT_ACTIVITY_NOT_SET_VALUE,
  MAX_ATTEMPS_STATUS_UPDATE,
  DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE,
  DELAY_TO_UPDATE_STATUS,
  DELAY_LAUNCH_REFRESH,
  DELAY_BEFORE_RECONNECT,
  DELAY_FOR_STATELESS_SWITCH_UPDATE,
  DELAY_FOR_SLIDER_UPDATE,
  DELAY_FOR_MACRO,
  DEVICE_TYPE,
  ACTIVITY_TYPE,
  DEVICEMACRO_TYPE,
  HOME_TYPE,
  SEQUENCE_TYPE,
  GENERALMUTE_TYPE,
  GENERALVOLUME_TYPE,
  GENERALVOLUMEUP_TYPE,
  GENERALVOLUMEDOWN_TYPE,
  DEFAULT_VOLUME,
  HUB_CONNECT_TIMEOUT,
  HUB_SEND_TIMEOUT,
  MAX_SOCKET_ERROR,
  DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS,
  DELAY_FOR_AUTO_DISCOVERY,
  PLUGIN_IDENTIFIER,
  PLATFORM_NAME,
};

export default {
  TIMEOUT_REFRESH_CURRENT_ACTIVITY,
  CURRENT_ACTIVITY_NOT_SET_VALUE,
  MAX_ATTEMPS_STATUS_UPDATE,
  DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE,
  DELAY_TO_UPDATE_STATUS,
  DELAY_LAUNCH_REFRESH,
  DELAY_BEFORE_RECONNECT,
  DELAY_FOR_STATELESS_SWITCH_UPDATE,
  DELAY_FOR_SLIDER_UPDATE,
  DELAY_FOR_MACRO,
  DEVICE_TYPE,
  ACTIVITY_TYPE,
  DEVICEMACRO_TYPE,
  HOME_TYPE,
  SEQUENCE_TYPE,
  GENERALMUTE_TYPE,
  GENERALVOLUME_TYPE,
  GENERALVOLUMEUP_TYPE,
  GENERALVOLUMEDOWN_TYPE,
  DEFAULT_VOLUME,
  HUB_CONNECT_TIMEOUT,
  HUB_SEND_TIMEOUT,
  MAX_SOCKET_ERROR,
  DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS,
  DELAY_FOR_AUTO_DISCOVERY,
  PLUGIN_IDENTIFIER,
  PLATFORM_NAME,
};
